name: Build and Publish Go Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Build binaries
      run: |
        make build

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
        files: |
          scraper
          api
          mailer